stages:
  - build
  - deploy_gcp

build_images:
  stage: build
  image: docker:20.10.16

  services:
    - docker:20.10.16-dind

  variables:
    DOCKER_TLS_CERTDIR: "/certs"

  before_script:
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASS

  script:
    - docker build -t victorbruno221/app-cicd-dio:2.0 app/.
    - docker push victorbruno221/app-cicd-dio:2.0

deploy_gcp:
  stage: deploy_gcp
  before_script:
    - chmod 400 $SSH_KEY

  script:
    - ssh -o StrictHostKeyChecking=no -i $SSH_KEY gcp@$SSH_SERVER "sudo rm -rf ./app-cicd-dio/ && ls -la && pwd && git clone git@gitlab.com:Bruno_victor/app-cicd-dio.git && cd app-cicd-dio && chmod +x ./script.sh && ./script.sh"
